### PR TITLE
Use oxford fonts

### PR DESCRIPTION
**Pull request by abhidg**

### CODE REVIEW

**Comment by fcooper8472** [comment]
I've just built locally with the new fonts, and I'm not a big fan!

It doesn't look as easy to read, to me.  What are the benefits of using these fonts?  Happy to hear what everyone else thinks, too!

**Comment by martinjrobins** [comment]
I'm fairly ambivalent, but leaning towards keeping the existing fonts as I prefer no serifs

**Comment by martinjrobins** [comment]
closing this unless anyone has an objection?

**Comment by martinjrobins** [comment]
closing this unless anyone has an objection?

**Pull request closed without merging**
