### PR TITLE
Remove need to specify username in the deployment script

### PR DESCRIPTION
**Pull request by iamleeg**
Use my local username if I didn't give a different one on the command line.

### CODE REVIEW

**Comment by abhidg** [comment]
Since rsync uses ssh here, you can put the username in the SSH config, then no need to write username everytime.

**Comment by fcooper8472** [comment]
fair enough...

**Comment by iamleeg** [comment]
> Is your local username ever likely to match with the random username that the CS department assigned you for logging in to their linux server?

Yes, because I set up my local username to be the same as my remote username for convenience.

**Comment by iamleeg** [comment]
I'm going to abandon this PR. The "correct" way to deal with this is, as @abhidg suggests, to set up `.ssh/config`, which makes it harder to use for people who are used to doing the username thing. So let's just leave the username there.

**Pull request closed without merging**
